### ISSUE TITLE
dynamic tab,how to do?

### ISSUE THREAD

**Issue by smile2014** [mashhoodr/angular2-multicomponent-form#4]
http://demo.b-jui.com/

**Comment by mashhoodr** [comment]
@smile2014 you can pass it a list of JSON and then render it accordingly. Anywhere specific where you are having issues?

**Comment by smile2014** [comment]
@mashhoodr  thank you  ,When I  click menu add a TAB, at the same time the corresponding components to bind to the content. But switch the TAB page will cut will be the original Tab  page data will be cleared

**Comment by mashhoodr** [comment]
@smile2014 looks like you need to persist the state in a service in order to get this to work

**Comment by smile2014** [comment]
@mashhoodr  Thank you
